### ISSUE TITLE
AROMA is broken

### ISSUE THREAD

**Issue by mfonville** [opengapps/opengapps#56]
Aroma build is broken since we have implemented the compression method.

Suspicion is that there might be lack of RAM because AROMA also needs some memory, while extracting whole gmscore to /tmp/ (which is also fully in RAM) takes e.g. 150MiB.

so, you get a big pressure on RAM, which might even be the problem for some people who are having trouble installing the current 'stock' package:
* Aroma takes RAM
* TWRP takes RAM
* a .xz file gets unzipped into /tmp/ which takes RAM
* the .xz gets further extracted (150MiB) into /tmp/ which takes RAM
* the extraction process of the xz-file also takes RAM

**Comment by rapperskull** [comment]
Do we have logs to analyze?
One thing we can think of, if the memory is the real problem, is to only generate the config file with the AROMA zip and then let the user flash the stock package. It's however the worst case scenario.

**Comment by kronflux** [comment]
Aroma restarts TWRP halfway through flash. Here's all I have for a log:

I:Set page: 'install'
I:Set page: 'flash_confirm'
I:Set page: 'flash_zip'
I:operation_start: 'Flashing'
Installing '/sdcard/flashable_zips/open_gapps-arm-5.1-aroma-20150710.zip'...
Checking for MD5 file...
Skipping MD5 check: no MD5 file found
I:Zip does not contain SELinux file_contexts file in its root.
I:Legacy property environment initialized.
aroma/s: Initializing
Starting AROMA Installer version 2.70RC2
     (c) 2013 by amarullz xda-developers

Starting AROMA Installer version 2.70RC2
(c) 2013 by amarullz xda-developers

aroma/s: Mute Parent
aroma/s: Saving Arguments
aroma/s: Open Archive
aroma/s: Initializing Resource
aroma/s: Opening Freetype
aroma/s: INDR Input Device: hs_detect (event3) - Class : 1
aroma/s:   VKN : 0, CALIB : (0,0,0,0)
aroma/s: INDR Input Device: touch_dev (event1) - Class : 6
aroma/s:   VKN : 0, CALIB : (0,1079,0,1919)
aroma/s: INDR Input Device: qpnp_pon (event0) - Class : 1
aroma/s:   VKN : 0, CALIB : (0,0,0,0)
aroma/s: INDR Input Device: gpio-keys (event2) - Class : 1
aroma/s:   VKN : 0, CALIB : (0,0,0,0)
aroma/s: Starting Interface
aroma/s: (1) Freetype fonts loaded as Font Family
aroma/s: (1) Freetype fonts loaded as Font Family
__bionic_open_tzdata: couldn't find any tzdata when looking for posixrules!
Starting TWRP 2.8.7.0 on Fri Jul 10 21:23:02 2015
 (pid 1380)

**Comment by mfonville** [comment]
I made an alternative build that copied the extracted xz files not to /tmp but another location, and even if not perfect it looks promising, because it doesn't crash.

My proposal would be to make sure we mount /cache and put our temporary extractions on that filesystem (and to clean them up afterwards)

**Comment by mfonville** [comment]
I tested it, but it doesn't solve the problem, so I will not merge it...

**Comment by MyPictures** [comment]
Where do you think the issue would be otherwhise mfonville?

**Comment by mfonville** [comment]
I really have no idea. What btw also 'worries' me, is that before any installation of new files is executed, the removals should be performed. But when people try the aroma, the removals are not even not executed (it crashes even before that), which would mean that the Aroma installer does probably not even reach the new uncompression part.

**Comment by MyPictures** [comment]
I wonder if this is a TWRP issue only or if other recoveries are also affected.

**Comment by mfonville** [comment]
Hmm, I was wrong. It does run the app-removals, and it *does* remove the apps. It does fail at the install part... in some way that is really comforting...

**Comment by mfonville** [comment]
I now tried compressing with -6e instead of -9e, which should require much less RAM on the decompressing device, but it did not help. I really have really no clue anymore...

**Comment by MyPictures** [comment]
On what phone are you testing on?

**Comment by mfonville** [comment]
GT-i9300

**Comment by MyPictures** [comment]
The only one I could think of would be "PhilZ Touch" I assume.

**Comment by mfonville** [comment]
Well, if you'd have the resources you could try it then maybe with that recovery? It is still a pity that @amarullz is not able to help us out with this one because he is so busy with the new libaroma.

**Comment by bgiesing** [comment]
@mfonville @raulx222 @rapperskull  I might have found the issue... Do you think it could be a error with Syntax considering the last three commits to the `inc.aromadata.sh` file was the same build that all the issues started? I tried reverting them locally and building, but signapk.jar is giving me this error so I can't test:

```java
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:3236)
        at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
        at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
        at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
        at java.util.zip.ZipOutputStream.write(ZipOutputStream.java:340)
        at orig.SignApk.copyFiles(SignApk.java:455)
        at orig.SignApk.main(SignApk.java:504)
ERROR: Creating Flashable ZIP-file failed
```

Any one of you guys want to make a test build?

**Comment by mfonville** [comment]
Will do

**Comment by MyPictures** [comment]
@bgiesing How much memory do you give the java VM for SignApk ?

**Comment by bgiesing** [comment]
@MyPictures I don't even know cause I have never used SignApk before... Last time I made a ZIP was on July 6 when they still used the shell method to sign.

**Comment by mfonville** [comment]
You can also use the zip without the signature...

**Comment by bgiesing** [comment]
@mfonville Except when that error appeared, the zip was deleted.

**Comment by mfonville** [comment]
@bgiesing that should not happen. If the signing fails, it doesn't delete the file (it here never does).

**Comment by bgiesing** [comment]
Well, here's where it said it would be: `opengapps/out/open_gapps-arm-5.1-aroma-20150711.zip` and here's what's in the folder:
```sh
[bgiesing@manjaro opengapps]$ ls out/
open_gapps-arm-5.1-stock-20150706.zip
```

**Comment by mfonville** [comment]
Look for /build/arm/22/aroma.zip

**Comment by bgiesing** [comment]
@mfonville Why didn't I think of that...

![facepalm](http://i.giphy.com/iGNiqAuwG9dwQ.gif)

Testing now.

**Comment by bgiesing** [comment]
@mfonville Still crashes plus recovery log is overwritten so I can't get that and gapps log never generated cause of the reboot...

**Comment by MyPictures** [comment]
How big is the /cache partition on other devices?: http://goo.gl/mBPBkD
I don't think 250 (my cache) would be enough for the uncompressed gapps files which reach  up to 700 MB .

**Comment by bgiesing** [comment]
@MyPictures My tablet (2013 Nexus 7) is 551MB and phone (Moto G) is 651MB

**Comment by mfonville** [comment]
/cache/ is not used, only /tmp/, I forfeited that plan since it didn't help.

But for your information: only the intermediate extraction of the .tar.xz was done there in my experimental build, one at a time, to /cache, so at any give time at most 30MiB was used.

**Comment by MyPictures** [comment]
I increased /tmp tmpfs to 2 GB and still same freezing issue.

**Comment by MyPictures** [comment]
The strange thing is that I can flash the stock opengapps just fine but the aroma one always files. I would say they extract about the same size?
Would it be crazy to like maybe try the default aroma theme?

**Comment by mfonville** [comment]
If i comment out the folder_extract operations, aroma doesn't crash (and it almost instant ready), so it *must* be triggered by one of the advanced operations thats are executed by that function.

**Comment by MyPictures** [comment]
So the issue is defently not caused by running out of memory/ram/tmp space. I saw that some other guys had the same issue on the stock package which I strangely cant reproduce.

Not sure where to go from here...

**Comment by mfonville** [comment]
The guy with the problem from the stock package is now resolved. He was not using aroma, but he was using a theme for TWRP, and my suspicion is that the theme somehow triggered the reboot.
But it also still might be a bug within TWRP, e.g. that somehow we are writing to some memory which should be reserved for TWRP.
Maybe someone from @TeamWin could help us?

**Comment by mfonville** [comment]
Oh, hell, I got a fix! Bundling our own xz decompression does the trick.

**Comment by mfonville** [comment]
I added some code that will always enable xz decompression with the bundled binary, which should resolve this bug.

**Comment by MyPictures** [comment]
So when will you trigger a new build with the latest xz changes @mfonville?

**Comment by mfonville** [comment]
It is automatically triggered at 2:15 CEST. (so around 0:15 UTC) and takes around an hour to build and upload, if GitHub has no connectivity issues (which was surprisingly last night for the first time in a very very long time).

**Comment by MyPictures** [comment]
Thanks, unfortunately It still freezes and reboots for me, I just used the opengapps config file together with the stock apps for now.

**Comment by mfonville** [comment]
I now made a larger stock package, and TWRP did crash for me with it, using the built-in decompressor. So we might even have to turn on xzdec for *all* arm-builds (for now), and file a bug with TWRP.

**Comment by MuSamDu** [comment]
Anyway, it still freezes for me... I downloaded the latest version (open_gapps-arm-6.0-aroma-20151209.zip), and i verified the md5sum which it correct. Really no solution? Plz help me!!!

**Comment by mfonville** [comment]
@MuSamDu If Aroma doesn't work for you, I am sorry we cannot do anything within our power to fix it. We are completely dependent on the AROMA-Installer developer amarullz. You will have to use one of the non-Aroma packages instead.

**Comment by MuSamDu** [comment]
I didn't mean to give up using aroma installer, im trying to see if we can solve the problem. im using Oneplus One with CM 13.
I heard that i'll have to write a config file myself if i use any other builds rather than aroma, and i've no idea about how to do that. (just take me as a fool) links to tutorials? Thanks!!!

**Comment by mfonville** [comment]
https://github.com/opengapps/opengapps/wiki/Advanced-Features-and-Options#the-gapps-config-file

But you could easily find that yourself, if you need any help, please use the XDA Q&A. Because I rather focus on development.

**Comment by madmax2** [comment]
Yeah, aroma freezes when I try to install it with TWRP..

Also cannot install stock or full GAAPS either..
Only the mini GAAPS or smaller can be installed.

**Comment by Germano0** [comment]
I confirm that TWRP (3.0.2) reboots while installing Aroma for Android 7.1

**Comment by nikhil2209** [comment]
I didn't have reboots previously but now I do. Strange thing is, after one reboot, the aroma installer works just fine and installation completes successfully.

**Comment by mfonville** [comment]
@nikhil2209 it is related to amount of RAM available on the phone, Aroma has a memory leak and that kills the installer at some point.

We ourselves cannot fix this, only the aroma-dev himself, but he stopped development a long time ago.

**Comment by nikhil2209** [comment]
Ah, I see. But the problem occurs only a few times. For example, I today installed the latest version, 5th February, and installation completed without any reboots. For me, the problem occurs only when flashing the ROM and Gapps one after another (having previously put them in the queue). If I manually first flash ROM, then Gapps, no problem occurs. My phone has 2Gb of RAM, still not sufficient :( 
I guess I can live with it installing, at least. :)

**Comment by MathijsG** [comment]
On my Galaxy S5 with TWRP it crashes almost at the beginning immediately, and reboots after a few seconds. Why not remove the AROMA option when it's not working and not being updated anymore?
