### ISSUE TITLE
Pixel launcher crashes on android 9

### ISSUE THREAD

**Issue by eth481642** [opengapps/opengapps#727]
After installing Lineage OS 16.0 with latest opengapps(stock variant) on Nexus 6, pixel launcher crashes. It looks like there is some kind of permission problem

> 03-25 18:04:17.889   750  7019 W ActivityManager: Permission Denial: setShelfHeight() from pid=8517, uid=10012 requires android.permission.STATUS_BAR
03-25 18:04:17.890  8517  8517 D AndroidRuntime: Shutting down VM
03-25 18:04:17.891  8517  8517 E AndroidRuntime: FATAL EXCEPTION: main
03-25 18:04:17.891  8517  8517 E AndroidRuntime: Process: com.google.android.apps.nexuslauncher, PID: 8517
03-25 18:04:17.891  8517  8517 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity 
03-25 18:04:17.909   750   766 I ActivityManager: Showing crash dialog for package com.google.android.apps.nexuslauncher u0

**Comment by NicholasBuse** [comment]
The only solution that I know of for this err is already in place for the Pixel Launcher:

https://gitlab.nezorfla.me/opengapps/all/blob/master/etc/permissions/privapp-permissions-google.xml#L117

**Comment by eth481642** [comment]
But it still crashes
I tried manually grant that permission but it also failed

> adb shell pm grant com.google.android.apps.nexuslauncher android.permission.STATUS_BAR
Security exception: Package com.google.android.apps.nexuslauncher has not requested permission android.permission.STATUS_BAR

I also found people on Reddit having the same issue and one man wrote this:

> The issue is that Pixel launcher uses a hidden API and a permission which is only able to be allowed with "framework" signature. That means it must have the same signature with ROM, which is impossible. Some roms tend to remove the permission check 

Can it be the cause of problem?

**Comment by frankwalter1300** [comment]
Same problem with lineage os 16.

**Comment by Trogie** [comment]
Same problem: oneplus 3t, lineage 16, apk installed in /system/app and given all permissions.

**Comment by frankwalter1300** [comment]
I deleted pixel launcher from adb and also from adb I installed an alternative launcher.

**Comment by imydou** [comment]
https://forum.xda-developers.com/pixel-xl/development/rom-lineage-16-0-pixels-sailfish-marlin-t3830083/post78029447#post78029447

**Comment by eth481642** [comment]
Yesterday one man wrote an answer on stackexchange. It seems that he managed to solve an issue

https://android.stackexchange.com/questions/212860/pixel-launcher-crashing-due-to-missing-status-bar-and-manage-activity-stacks-per

Can anyone try it on your devices?

**Comment by dmohns** [comment]
I followed the steps from StackOverflow (https://android.stackexchange.com/a/212861) and now the launcher works 🎉

I don't fully understand whose responsibility the permissions are. Can it be fixed within OpenGAPPS or does it have to be fixed on LineageOS side?

**Comment by kyvaith** [comment]
The real solution is here [XDA](https://forum.xda-developers.com/showpost.php?p=78029447&postcount=483). IMO it shoud be integrated with gapps package hence it adds missing apk file.

**Comment by stucki** [comment]
The solution mentioned by @eth481642 works. Is there any chance to integrate this fix so that no manual editing is needed?

**Comment by nezorflame** [comment]
@NicholasBuse ^

**Comment by NicholasBuse** [comment]
android.permission.STATUS_BAR was there, but I added android.permission.MANAGE_ACTIVITY_STACKS in https://gitlab.opengapps.org/opengapps/all/commit/00eb9a8f5ea20f91b715bf94c25e269208a76a21

**Comment by lorber13** [comment]
Still crashes with latest opengapps lineageos 16

**Comment by curiousrom** [comment]
> Still crashes with latest opengapps lineageos 16

Is that on a clean install (format Data & System wipe)?

If yes & you really want to help solve the problem: reboot, reproduce the error & capture a logcat that you can attach to your reply.

BTW "latest" won't mean a thing after the next update so including the build date of both Open GApps (package?) & ROM is good practice IMO. Also the device model.

**Comment by lorber13** [comment]
Edited... It is not a clean install... I took a logcat which says pixel launcher asks for permission android.permission.STATUS_BAR

**Comment by Yihao-G** [comment]
Adding `STATUS_BAR` and `MANAGE_ACTIVITY_STACKS` indeed solves the problem.

However, if you are having problems with the "recent view" doesn't show app suggestions at the bottom of the screen when "swipe up on home button" option is enabled, or if you don't have "swipe up on home button" option under Settings > Gestures, install QuickSwitch in Magisk and switch the provider to Pixel launcher should fix the problem.

**Comment by lorber13** [comment]
Clean flashed lineageos oneplus3 build 2019-10-18 with opengapps micro 2019-10-17... Still crashes

**Comment by lukasz1992** [comment]
2019-11-09 the problem still exists in opengapps (stock) and confirm the fix works

**Comment by codevalley** [comment]
> 00eb9a8f5ea20f91b715bf94c25e269208a76a21

Can't see this commit.

**Comment by nezorflame** [comment]
> > android.permission.STATUS_BAR was there, but I added
> > android.permission.MANAGE_ACTIVITY_STACKS in https://gitlab.opengapps.org/opengapps/all/commit/00eb9a8f5ea20f91b715bf94c25e269208a76a21
> 
> Can't see this commit.

We've recreated the repos from scratch, so yeah, it can't be seen. I'll send a link with the place a bit later.

**Comment by nezorflame** [comment]
> Adding `STATUS_BAR` and `MANAGE_ACTIVITY_STACKS` indeed solves the problem.
> 
> However, if you are having problems with the "recent view" doesn't show app suggestions at the bottom of the screen when "swipe up on home button" option is enabled, or if you don't have "swipe up on home button" option under Settings > Gestures, install QuickSwitch in Magisk and switch the provider to Pixel launcher should fix the problem.

With the release of Q, we're gonna also provide an overlay which will set the Pixel Launcher as the default one without the need of QuickSwitch.

**Comment by lukasz1992** [comment]
I still have this problem after LineageOS update, adding permissions to /data/system/packages.xml is sometimes still necessary. I tried erasing addon.d script, reflashing rom and reflashing gapps - one time it helped and another it did not.

I never cleaned my /data partition, maybe that is the reason.

**Comment by DXist** [comment]
I installed opengapps with Carbon ROM based on Android 10 on Nexus 6.

The system reloads often, Google Camera and apps that use geolocation trigger system reloads.

**Comment by nezorflame** [comment]
@DXist this is a wrong place to report this issue. Please head over to XDA and create a post there in you  device's section.

**Comment by osm0sis** [comment]
Purging issues. Feel free to request reopening if it is still reproducible on the latest build.
